### ISSUE TITLE
SNMP OID's returns error in snmpwalk when there is container inside container

### ISSUE THREAD

**Issue by doron2020** [clicon/clixon#395]
Hi, this is Siklu team
We are trying to enter SNMP OID's inside a yang txt file. It seems to work OK with a simple list inside an container, but not if the container is nested inside another container.  

error looks like this:

doronb@dali:~$ snmpwalk -v2c -c public 10.40.0.156 iso.3.6.1.2.1.31926.35.3
iso.3.6.1.2.1.31926.35.3.1.1.6.100.111.114.111.110.49 = STRING: "doron1"
iso.3.6.1.2.1.31926.35.3.1.1.6.100.111.114.111.110.50 = STRING: "doron2"
iso.3.6.1.2.1.31926.35.3.1.1.6.100.111.114.111.110.53 = STRING: "doron5"
iso.3.6.1.2.1.31926.35.3.1.1.6.100.111.114.111.110.53 = OID: iso.3.6.1.2.1.31926.35.3.1.2
Error: OID not increasing: iso.3.6.1.2.1.31926.35.3.1.1.6.100.111.114.111.110.53
 >= iso.3.6.1.2.1.31926.35.3.1.1.6.100.111.114.111.110.53

Attached  the yang file
[radio-bridge-tg-radio-dn.yang.txt](https://github.com/clicon/clixon/files/10352939/radio-bridge-tg-radio-dn.yang.txt)

thanks!

**Comment by shmuelhazan** [comment]
@doron2020 Maybe it would be helpful to give a more specific example for a problematic scenario. The yang in the example is very large.

**Comment by krihal** [comment]
Hi,

Any chance you can share the MIB for this with us? When we implemented this we used the tool smidump to convert from MIBs to YANG according RFC 6643, this means that not all YANGs can be mapped back to MIBs.

BR

**Comment by StasSt-siklu** [comment]
SNMP does not accept yang types int8, int16 etc. Only int32

**Comment by olofhagsand** [comment]
@StasSt-siklu :
```
SNMP does not accept yang types int8, int16 etc. Only int32
```
What does this comment signify? 
Does it mean that the issue is not relevant and couldbe closed, or is the issue still relevant?

**Comment by StasSt-siklu** [comment]
Issue snmpwalk return error when there is container inside container not relevant.
SNMP does not accept yang types int8, int16 etc. , only int32 is another issue)

**Comment by olofhagsand** [comment]
If the issue is not relevant can you please close it?
The issue with int types I  suppose is not a clixon issue?
